In [1]:
import numpy as np

In [9]:
a = [1, 2, 3, 4, 5] * 100000
b = np.array(a)
len(b)

500000

In [10]:
%%timeit -n1 -r10
[x * 2 for x in a]

65.5 ms ± 8.41 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [11]:
%%timeit -n1 -r10
b * 2

2.54 ms ± 355 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [14]:
%%timeit -n1 -r20
sum(a)

7.23 ms ± 1.49 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)


In [16]:
%%timeit -n1 -r20
b.sum()

453 µs ± 144 µs per loop (mean ± std. dev. of 20 runs, 1 loop each)


In [29]:
c = np.array([[1, 2], [3, 4], [5, 6]])
print(c)
print(len(c))
print(c.size)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
3
6
(3, 2)


In [40]:
d = np.arange(6)
d = d.reshape((3, 2))
print(d)
c * d

[[0 1]
 [2 3]
 [4 5]]


array([[ 0,  2],
       [ 6, 12],
       [20, 30]])

In [76]:
e = np.arange(25).reshape((5,5))
print(e)
e[1:3, 1:-2]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7],
       [11, 12]])

In [60]:
f = np.arange(25).reshape((5,5))
f[f % 3 == 0] = 200
f

array([[200,   1,   2, 200,   4],
       [  5, 200,   7,   8, 200],
       [ 10,  11, 200,  13,  14],
       [200,  16,  17, 200,  19],
       [ 20, 200,  22,  23, 200]])

In [62]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
x = np.arange(12).reshape((4,3))
x + [10, 20, 30]

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38],
       [19, 30, 41]])

In [73]:
p = np.array([5, 10, 15])
p.reshape((1, 3))


array([[ 5, 10, 15]])